apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.vaultSecretName}}
type: Opaque
stringData:
  vaulturl: "<path:essential-services/data/vault-info#VAULT_URL>"
  vaulttoken: "<path:essential-services/data/vault-info#VAULT_TOKEN>"
